name: checking Docker Image is Building or not in on PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          tags: asia-south1-docker.pkg.dev/eremote-hire-website-405811/testing/nextjs
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
