name: checking Docker Image is Building or not in on PR to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - id: "auth"
        uses: "google-github-actions/auth@v2.1.2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2.1.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Configure Docker
        run: gcloud auth configure-docker \
          asia-south1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: asia-south1-docker.pkg.dev/eremote-hire-website-405811/testing
          cache-from: type=gha
          cache-to: type=gha,mode=max
